### ISSUE TITLE
Investigate obfuscating ciphertext

### ISSUE THREAD

**Issue by keur** [XCF-Babble/babble#23]
A [paper](https://arxiv.org/abs/1909.01496) was released recently that describes novel methods for encoding text inside of a language model. The example implementation can be found [here](https://steganography.live). Babble could give users the option to hide their text this way. 

Because this requires mountains of work, this is mostly here as a reminder and will not be worked on anytime soon.

**Comment by keur** [comment]
After some brief investigation I have decided this will not be feasible. Just the `pytorch` download is over half a gigabyte, and the neural net very likely requires GPUs to perform efficiently. This will be too much overhead for users. We would need to setup an API for the extension to hit, and I would prefer to keep everything client side.

**Comment by yvbbrjdr** [comment]
Oh RIP.
