### ISSUE TITLE
Clean up webpack

### ISSUE THREAD

**Issue by keur** [XCF-Babble/babble#25]
- [ ] `webpack` and its dependencies are vendoring themselves. Figure out how to not do this if possible since one of its dependencies, `bluebird`, runs `eval` 3 times!

- [ ] split `vendor.js` into multiple files so we can split up dev dependencies our project files to lighten the load on some pages that don't need to pull in everything

**Comment by yvbbrjdr** [comment]
Seems like we stopped trying to remove `eval`s.
