### ISSUE TITLE
The plugin does not work with CalNet ID SSO

### ISSUE THREAD

**Issue by yvbbrjdr** [XCF-Babble/babble#64]

**Comment by abizer** [comment]
getting anything to authenticate against calnet requires being on CalNet CAS' domain whitelist

**Comment by keur** [comment]
Update: only fails on Firefox

**Comment by yvbbrjdr** [comment]
Also breaks bjb

**Comment by dkess** [comment]
https://github.com/XCF-Babble/babble/blob/master/src/content/inject.ts#L28 overrides `window.onload`.
