### ISSUE TITLE
Make Argon parameters tweakable

### ISSUE THREAD

**Issue by keur** [XCF-Babble/babble#80]
Suggested [here](https://www.wilderssecurity.com/threads/browser-extension-for-encryption-on-sites-that-dont-support-it-natively.421801/#post-2861954). This would be for advanced users that have higher memory devices. Since we aren't targeting mobile, we could also bump the memory usage to be higher than 64MB. We would want some advanced options menu for this.

**Comment by keur** [comment]
We might want to increase the default iterations for Argon, even if it makes the derivation slower. Right now we are using mobile/interactive settings. https://eprint.iacr.org/2016/759.pdf

**Comment by yvbbrjdr** [comment]
How is it going to increase the security?

**Comment by yvbbrjdr** [comment]
I mean, by generating or exchange a UUID, we already have 128 bits of security.

**Comment by yvbbrjdr** [comment]
Close due to [Yuki2718](https://www.wilderssecurity.com/threads/browser-extension-for-encryption-on-sites-that-dont-support-it-natively.421801/#post-2862514).
